### ISSUE TITLE
PackSharp - Visual Studio Marketplace Overview

### ISSUE THREAD

**Issue by davidherrera83** [ElSnoMan/PackSharp#10]
**Original:** "The extension is a palette of commands. Simply open the Command Palette (Shift + Command + P) and type 'packsharp' to begin."

**Suggest:** "The extension is a palette of commands. Simply open the Command Palette Mac:(Shift + Command + P) Windows: (Ctrl + P) and type 'packsharp' to begin."

**Comment by ElSnoMan** [comment]
@davidherrera83 Thanks for the windows-side suggestion. Please let me know if you find any other issues on Windows.

**Comment by ElSnoMan** [comment]
released in 2.0.0
