### ISSUE TITLE
Driver folder is not downloading when running PackSharp:Bootstrap Selenium command

### ISSUE THREAD

**Issue by EkpesJames** [ElSnoMan/PackSharp#21]
I am currently running version 2.2.3
When I run Bootstrap selenium, the below items are added successfully
 "nunit" 
 "NUnit3TestAdapter"
 "Microsoft.NET.Test.Sdk"
  "Selenium.Support" 
  "Selenium.WebDriver"

But the -Driver folder is not added to the project with error 'Request failed with status code 404'

**Comment by ElSnoMan** [comment]
When PackSharp looks for the latest chrome version, it returns "soon", so the URL it tries to 
download from is:

https://chromedriver.storage.googleapis.com/soon/chromedriver_mac64.zip

which doesn't exist and results in a 404.

Fortunately the tests will make this pretty easy to debug and test. Solution incoming...

**Comment by EkpesJames** [comment]
Thanks for the update, the link there looks like it's trying to download the mac one, am trying to bootstrap the window version. Isn't that an issue too?

**Comment by ElSnoMan** [comment]
That's just because my current machine is a Mac. I have it detect which OS it's currently on and grab the appropriate executable

**Comment by EkpesJames** [comment]
Ok, when is the fix coming?

**Comment by ElSnoMan** [comment]
Just published it. Update PackSharp to version 2.3.1
