### ISSUE TITLE
Packsharp: Bootstrap Selenium does not download driver folders for Mac

### ISSUE THREAD

**Issue by JHeroGR** [ElSnoMan/PackSharp#24]
I have been running the command Packsharp: Bootstrap Selenium on my specific tests folder, but when I run it, I receive an error request 404, I understand this issue has been resolved, but I updated packsharp, reinstalled it, and the drivers is still not showing in my project.

What I am using:
- VS Code on Mac
- .Net Core 3.1

**Comment by ElSnoMan** [comment]
version 2.3.2 solves the 404 issue. Instead of web scraping for the version, I am just calling their API endpoint with the latest version so it's more stable
