### ISSUE TITLE
Could not find project or directory

### ISSUE THREAD

**Issue by josersleal** [ElSnoMan/PackSharp#6]
Great extension, Thank you

I keep getting "Could not find project or directory" when trying to add new packages

It seems that the name of the project is passed without the extension. "projectname" versus "projectname.csproj".

**Comment by ElSnoMan** [comment]
Hi @josersleal,

Thanks for submitting this! Could you give me the file hierarchy so I can check this out? `dotnet add [PROJECT] package [PACKAGE]` does work without needing the .csproj extension, so I wonder if it's a pathing issue.

**Comment by ElSnoMan** [comment]
I'm thinking of grabbing the .csproj file, getting its path, and just putting its path with project name in the [PROJECT] option.

That should handle the pathing issues. I'll include this in the next update. Thanks again!

**Comment by ElSnoMan** [comment]
Update PackSharp and you should have the fix in. Here's the release:

#7
